Dependency injection for storage, codeowners
future-stardust/url-shrtnr-mystandstarplatinum pull request #3
Opened 2021-02-27 18:53 UTC by AlexPraefectus

* Added StorageFactory which is responsible for Storage being a singleton
* Added StorageConfig which introduces methods to read config from application.yml
* Added methods to Main which allow to get domain-related namespaces
(with docstring guidelines of how to use and how to add new)

Draft until https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/2 is not merged

2021-03-02 22:14 UTC, maza4aka requested changes
Check my comments and resolve conflicts!

2021-03-02 22:14 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/storage/namespace/HashParts.java
> +  }
so, instead of storing low and high bits, hash can be used, and _these_ methods can act as **computed properties**, returning masked value, e.g. `return hash & LOW_MASK`

2021-03-02 22:36 UTC, maza4aka commented
Plus, PR title doesn't illustrate it's contents: add Storage implementations + tests

2021-03-03 08:18 UTC, AlexPraefectus commented
@maza4aka PR is marked as "Draft" for reason :)  
It has contents of https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/2 (because I've made it while the first one was still waiting for review and its code was required to introduce DI).  
For now, there are no comments regarding non-merged code.

When these changes will be ready I'll request a review but for now, I'm closing discussions.
Still, You are free to open a PR with these changes.

2021-03-03 08:19 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/namespace/HashParts.java
> +  }
refer to https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/3#issuecomment-789529332

2021-03-03 08:19 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/namespace/HashParts.java
> +  private final int high;
refer to https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/3#issuecomment-789529332

2021-03-03 08:20 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/namespace/Container.java
> +public class Container {
refer to https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/3#issuecomment-789529332

2021-03-03 08:20 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/namespace/Container.java
> +  private final byte[] data;
refer to https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/3#issuecomment-789529332

2021-03-08 11:27 UTC, OlehKyba commented on src/main/java/edu/kpi/testcourse/storage/StorageFactory.java
> +  Storage storage() {
This code looks like Double-checked locking pattern. Please, check this article to see some Java issues with this technique: https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java

2021-03-08 11:50 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/StorageFactory.java
> +  Storage storage() {
As far as I understand, it will be ok if I'll change?
```java
private static Storage storage = null;
// to 
private static volatile Storage storage = null;
```

2021-03-08 12:02 UTC, OlehKyba commented on src/main/java/edu/kpi/testcourse/storage/StorageFactory.java
> +  Storage storage() {
:+1:

2021-03-08 12:10 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/storage/StorageFactory.java
> +  Storage storage() {
fixed

2021-03-08 12:12 UTC, OlehKyba approved these changes
( -_・)

2021-03-08 12:13 UTC, merged