Implement Auth service`s interface
future-stardust/url-shrtnr-mystandstarplatinum pull request #7
Opened 2021-03-13 11:49 UTC by maza4aka

* Auth implemented as singleton, same way as Storage
* AuthImpl has only some stubs for red tests (TODO: implement methods` logic)
* Some user login/creation (red) tests

2021-03-13 12:16 UTC, AlexPraefectus requested changes
Please take a look at the proposed changes.  
Let's discuss if something is not clear or You have any questions regarding my comments.

2021-03-13 12:16 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +  Auth auth() {
This implementation is not thread-safe and can cause lots of problems in multithreaded environments.

Please take a look at our discussion with @OlehKyba https://github.com/future-stardust/url-shrtnr-mystandstarplatinum/pull/3#pullrequestreview-606196942, there was a similar problem.

TL;DR you can make the method `synchronized to avoid problems.

2021-03-13 12:16 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/Auth.java
> +  AuthStatus loginUser(String username, String password);
I think that `loginUser` method should return JWT on success 🤔 

Unfortunately, we're not in Rust and are unable to bind types to enum values.  

Maybe, the most Java way is to return token and to throw custom Exceptions on errors.

2021-03-13 12:16 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/Auth.java
> +  AuthStatus createUser(String username, String password);
Returning enum value is legit but maybe this method should return void and throw Exceptions on errors?

I think that it will be more Java way of writing code and the interface of this method will also be similar to `loginUser` (after it will be changed)

2021-03-13 14:07 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +public class AuthFactory {
Idk, your Storage factory also produces singleton instance, what's the difference? Anyway, I`m happy that it works, at least.

2021-03-13 14:13 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +  Auth auth() {
Auth instance is created when initAuth is called inside Main method, not sure if it will cause problems. As for reading this object from multiple threads, it is still safe (except for directly working with Auth instance from multiple threads, which I doubt will eventually happen anyway).

2021-03-13 14:15 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/Auth.java
> +  AuthStatus loginUser(String username, String password);
Framework will do this automatically, as I understand. All I have to do is return whether user can login or not.

2021-03-13 14:21 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/Auth.java
> +  AuthStatus createUser(String username, String password);
Using enums to tell what's happened is much easier and cleaner for me. Also, interface for these two mentioned methods is already pretty consistent.

If you want to use exceptions, good for you, that's a matter of taste - propose your changes via PR, if you want.

2021-03-13 15:57 UTC, maza4aka commented
Auth service is almost implemented, only password hashing and Auth usage by AuthenticationProviderUserPassword is left for another PR.

2021-03-14 10:06 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +public class AuthFactory {
I used factory pattern to avoid many threads trying to initialize storage (which requires reading a lot of data from disk). And it also worked like barrier sync to wait until storage will be initialized.  
In this case, You can simply mark `Auth` class with `@Singleton` annotation and it will work the same way as it works now without factory.

2021-03-14 10:08 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +public class AuthFactory {
But as I have already stated before, current implementation with factory injection is pretty much good too :slightly_smiling_face:

2021-03-14 10:09 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +  Auth auth() {
It's very implicit contract IMHO.  
And marking method `synchronized`  will be a very "cheap" fix.

2021-03-14 10:24 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
this block can be simplified using one `if`:
```java
if (username == null || username.isEmpty()) {
  return AuthStatus.InvalidUsername;
}
```

2021-03-14 10:24 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
Same as username - can be simplified.  
Also, there's a DRY violation - String checks are absolutely the same for `username` and `password`

Maybe it would be a good idea to introduce method kinda `private bool checkStringNotEmpty(String s)` and move these checks there.

2021-03-14 10:24 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    } catch (NullPointerException e) {
as far as I remember, storage never throws

2021-03-14 10:24 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
Maybe it will be a good idea to simply propagate `usernameStatus` and `passwordStatus`

2021-03-14 10:24 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +      return AuthStatus.InvalidUsername;
User that does not exist and invalid data in the username should be different errors i think. With current implementation we're unable to process these errors separately (return different HTTP error codes for example)

2021-03-14 10:30 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
ok, indeed

2021-03-14 10:30 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
alright

2021-03-14 10:37 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    } catch (NullPointerException e) {
it throws NullPointer if username is null

2021-03-14 10:39 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    }
yup, ok

2021-03-14 10:44 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +      return AuthStatus.InvalidUsername;
I think, for security reasons, nobody outside should know if the user exists - if they provide some username and get InvalidUsername, no one will know if user even exists

2021-03-14 10:45 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    } catch (NullPointerException e) {
Well, this is invalid data for storage and can cause things to break if internal container will be changed from `Hashtable` to `HashMap` or something like this.
I think, it's better to check that data is not null before trying to use it with storage.

2021-03-14 10:47 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthFactory.java
> +  Auth auth() {
ok, why not

2021-03-14 10:50 UTC, maza4aka commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    } catch (NullPointerException e) {
but that's the contract your interface provides, at least in documentation. I shouldn't rely on it?

2021-03-14 10:51 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +    } catch (NullPointerException e) {
Oh, sorry, my bad, forgot that this is documented behaviour

2021-03-14 10:52 UTC, AlexPraefectus commented on src/main/java/edu/kpi/testcourse/auth/AuthImpl.java
> +      return AuthStatus.InvalidUsername;
Sounds reasonable :+1:

2021-03-14 10:52 UTC, AlexPraefectus approved these changes
LGTM :+1:

2021-03-14 10:53 UTC, merged

2021-03-14 10:56 UTC, maza4aka commented
@AlexPraefectus, I will restore this branch, if you don't mind) I will use it for the next two PRs.

2021-03-14 10:58 UTC, AlexPraefectus commented
Feel free to, it will be auto restored on your next push)
Just a habit to delete branches after merge)